export const BASE_URL = "https://61e55f2e595afe00176e553b.mockapi.io/products";

export const GET_PRODUCT_LIST_SUCCESS = "GET_PRODUCT_LIST_SUCCESS";
export const GET_PRODUCT_LIST = "GET_PRODUCT_LIST";
export const GET_PRODUCT_LIST_FAILURE = "GET_PRODUCT_LIST_FAILURE";

export const TOGGLE_LOADING = "TOGGLE_LOADING";

export const GET_PRODUCT_DETAILS = "GET_PRODUCT_DETAILS";
export const GET_PRODUCT_DETAILS_SUCCESS = "GET_PRODUCT_DETAILS_SUCCESS";
export const GET_PRODUCT_DETAILS_FAILURE = "GET_PRODUCT_DETAILS_FAILURE";

export const ADD_TO_CART = "ADD_TO_CART";

export const GET_CART_ITEMS = "GET_CART_ITEMS";
export const GET_CART_ITEMS_SUCCESS = "GET_CART_ITEMS_SUCCESS";
export const GET_CART_ITEMS_FAILURE = "GET_CART_ITEMS_FAILURE";

export const REMOVE_FROM_CART = "REMOVE_FROM_CART";

export const ADD_TO_RECENTLY_VIEWED = "ADD_TO_RECENTLY_VIEWED";

export const GET_RECENTLY_VIEWED_ITEMS = "GET_RECENTLY_VIEWED_ITEMS";
export const GET_RECENTLY_VIEWED_ITEMS_SUCCESS = "GET_RECENTLY_VIEWED_ITEMS_SUCCESS";
export const GET_RECENTLY_VIEWED_ITEMS_FAILURE = "GET_RECENTLY_VIEWED_ITEMS_FAILURE";

export const PLUS_MINUS_ITEM = "PLUS_MINUS_ITEM";

export const LOGGED_IN = "LOGGED_IN";
export const GET_USER = "GET_USER";